from odata_graph.ttl_to_py.defined_namespace_generator import generate_defined_namespace
from odata_graph.namespaces._QUDT_UNIT import QUDT_UNIT

# Conversion dictionary for OData4 units to QUDT types
# TODO: model units that are not in QUDT
UNIT_DICT = {
    "‰": {"unit": QUDT_UNIT.PERMILLE, "multiplier": None},
	"zie eenheid van productie": {"unit": None, "multiplier": None},
	"zie eenheid hoeveelheid": {"unit": None, "multiplier": None},
	"zie eenheid": {"unit": None, "multiplier": None},
	"years": {"unit": QUDT_UNIT.YR, "multiplier": None},
	"year": {"unit": QUDT_UNIT.YR, "multiplier": None},
	"x mln ton": {"unit": QUDT_UNIT.TONNE, "multiplier": 1000000},  # QUDT.MEGATONNE
	"x mln km": {"unit": QUDT_UNIT.KILOM, "multiplier": None},
	"x mln euro": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000},
	"x mln": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000000},
	"x mld": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000000000},
	"x million km": {"unit": QUDT_UNIT.KILOM, "multiplier": 1000000},
	"x million euros": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000},
	"x 1000 vte": {"unit": None, "multiplier": 1000},
	"x 1000 labour years": {"unit": QUDT_UNIT.YR, "multiplier": 1000},
	"x 1000 arbeidsjaren": {"unit": QUDT_UNIT.YR, "multiplier": 1000},
	"x 1000 ": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"x 1000": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"x 1.000": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"x 1,000 labour years": {"unit": QUDT_UNIT.YR, "multiplier": 1000},
	"x 1,000": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"x 1, 000": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"x 1 000 ton": {"unit": QUDT_UNIT.TONNE, "multiplier": 1000},
	"x 1 000 overnachtingen": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"x 1 000 m3": {"unit": QUDT_UNIT.M3, "multiplier": 1000},
	"x 1 000 labour years": {"unit": QUDT_UNIT.YR, "multiplier": 1000},
	"x 1 000 kgs": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000},
	"x 1 000 kg": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000},
	"x 1 000 euro": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000},
	"x 1 000 arbeidsjaren": {"unit": QUDT_UNIT.YR, "multiplier": 1000},
	"x 1 000 Labour years": {"unit": QUDT_UNIT.YR, "multiplier": 1000},
	"x 1 000 ": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"x 1 000": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"waarde uitgedrukt als % van het bbp": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"waarde": {"unit": QUDT_UNIT.COUNT, "multiplier": None},
	"volume-indexcijfers 2021=100": {"unit": None, "multiplier": None},
	"volume-index 2021=100": {"unit": None, "multiplier": None},
	"volume-index 2015=100": {"unit": None, "multiplier": None},
	"value as % of GDP": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"value": {"unit": QUDT_UNIT.COUNT, "multiplier": None},
	"uur per week": {"unit": QUDT_UNIT.HR_PER_NUM, "multiplier": None},
	"uur": {"unit": QUDT_UNIT.HR, "multiplier": None},
	"uren per week": {"unit": QUDT_UNIT.HR_PER_NUM, "multiplier": None},
	"uren per jaar": {"unit": QUDT_UNIT.HR_PER_YR, "multiplier": None},
	"uren per etmaal": {"unit": QUDT_UNIT.HR_PER_NUM, "multiplier": None},
	"uren": {"unit": QUDT_UNIT.HR, "multiplier": None},
	"trendklasse": {"unit": None, "multiplier": None},
	"tons dm": {"unit": None, "multiplier": None},
	"tonnes": {"unit": QUDT_UNIT.TONNE, "multiplier": None},
	"ton ds": {"unit": None, "multiplier": None},
	"ton": {"unit": QUDT_UNIT.TONNE, "multiplier": None},
	"somscore (0-6)": {"unit": None, "multiplier": None},
	"somscore (0-4)": {"unit": None, "multiplier": None},
	"scoring": {"unit": None, "multiplier": None},
	"score": {"unit": None, "multiplier": None},
	"schaalscore (0 - 10)": {"unit": None, "multiplier": None},
	"schaalscore": {"unit": None, "multiplier": None},
	"scale score": {"unit": None, "multiplier": None},
	"saldo positieve en negatieve antwoorden": {"unit": None, "multiplier": None},
	"reizigerskilometers": {"unit": QUDT_UNIT.KILOM, "multiplier": None},
	"ratio": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"rapportcijfer (1-10)": {"unit": None, "multiplier": None},
	"rapportcijfer": {"unit": None, "multiplier": None},
	"promille": {"unit": QUDT_UNIT.PERMILLE, "multiplier": None},
	"procentpunt": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"personen per 1 huishouden": {"unit": None, "multiplier": None},
	"percentage point": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"per vrouw": {"unit": None, "multiplier": None},
	"per km²": {"unit": QUDT_UNIT.NUM_PER_KILOM2, "multiplier": None},
	"per km2": {"unit": QUDT_UNIT.NUM_PER_KILOM2, "multiplier": None},
	"per huishouden": {"unit": None, "multiplier": None},
	"per 1000 inwoners": {"unit": None, "multiplier": None},
	"per 100 tussen gemeenten verhuisde personen": {"unit": None, "multiplier": None},
	"per 100 opnamen": {"unit": None, "multiplier": None},
	"per 100 moved persons between municipalities ": {"unit": None, "multiplier": None},
	"per 100 marriages": {"unit": None, "multiplier": None},
	"per 100 live born children": {"unit": None, "multiplier": None},
	"per 100 levend geboren kinderen": {"unit": None, "multiplier": None},
	"per 100 inwoners op 1 januari": {"unit": None, "multiplier": None},
	"per 100 inwoners": {"unit": None, "multiplier": None},
	"per 100 inhabitants on 1 January": {"unit": None, "multiplier": None},
	"per 100 huwelijkssluitingen": {"unit": None, "multiplier": None},
	"per 100 000 van gem. bev.": {"unit": None, "multiplier": None},
	"per 100 000 of the average population": {"unit": None, "multiplier": None},
	"per 100 000 inwoners": {"unit": None, "multiplier": None},
	"per 10 000 personen": {"unit": None, "multiplier": None},
	"per 10 000 of the population": {"unit": None, "multiplier": None},
	"per 10 000 inwoners": {"unit": None, "multiplier": None},
	"per 1,000 women aged 30 to 49": {"unit": None, "multiplier": None},
	"per 1,000 women aged 25 to 29": {"unit": None, "multiplier": None},
	"per 1,000 women aged 20 to 24": {"unit": None, "multiplier": None},
	"per 1,000 women aged 15 to 49": {"unit": None, "multiplier": None},
	"per 1,000 women aged 15 to 19": {"unit": None, "multiplier": None},
	"per 1,000 persons aged 80 or older": {"unit": None, "multiplier": None},
	"per 1,000 persons aged 65 to 79": {"unit": None, "multiplier": None},
	"per 1,000 persons aged 45 to 64": {"unit": None, "multiplier": None},
	"per 1,000 persons aged 15 to 44": {"unit": None, "multiplier": None},
	"per 1,000 non-Dutch nationals": {"unit": None, "multiplier": None},
	"per 1,000 married couples": {"unit": None, "multiplier": None},
	"per 1,000 live born children": {"unit": None, "multiplier": None},
	"per 1,000 inhabitants aged 1 to 4": {"unit": None, "multiplier": None},
	"per 1,000 inhabitants": {"unit": None, "multiplier": None},
	"per 1,000 inhabintants": {"unit": None, "multiplier": None},
	"per 1,000 girls": {"unit": None, "multiplier": None},
	"per 1,000 couples": {"unit": None, "multiplier": None},
	"per 1,000 children aged 5 to 14": {"unit": None, "multiplier": None},
	"per 1,000 born children": {"unit": None, "multiplier": None},
	"per 1,000 births": {"unit": None, "multiplier": None},
	"per 1,000": {"unit": None, "multiplier": None},
	"per 1 000 woningen": {"unit": None, "multiplier": None},
	"per 1 000 vrouwen van 30 tot 50 jaar": {"unit": None, "multiplier": None},
	"per 1 000 vrouwen van 25 tot 30 jaar": {"unit": None, "multiplier": None},
	"per 1 000 vrouwen van 20 tot 25 jaar": {"unit": None, "multiplier": None},
	"per 1 000 vrouwen van 15 tot 50 jaar": {"unit": None, "multiplier": None},
	"per 1 000 vrouwen van 15 tot 20 jaar": {"unit": None, "multiplier": None},
	"per 1 000 vrouwen": {"unit": None, "multiplier": None},
	"per 1 000 personen": {"unit": None, "multiplier": None},
	"per 1 000 niet-gehuwde vrouwen": {"unit": None, "multiplier": None},
	"per 1 000 niet-gehuwde mannen": {"unit": None, "multiplier": None},
	"per 1 000 niet-Nederlanders": {"unit": None, "multiplier": None},
	"per 1 000 meisjes": {"unit": None, "multiplier": None},
	"per 1 000 live born children": {"unit": None, "multiplier": None},
	"per 1 000 levendgeborenen": {"unit": None, "multiplier": None},
	"per 1 000 levend geborenen": {"unit": None, "multiplier": None},
	"per 1 000 levend geboren kinderen": {"unit": None, "multiplier": None},
	"per 1 000 kinderen van 5 tot 15 jaar": {"unit": None, "multiplier": None},
	"per 1 000 kinderen van 1 tot 5 jaar": {"unit": None, "multiplier": None},
	"per 1 000 inwoners van 80 jaar of ouder": {"unit": None, "multiplier": None},
	"per 1 000 inwoners van 65 tot 80 jaar": {"unit": None, "multiplier": None},
	"per 1 000 inwoners van 45 tot 65 jaar": {"unit": None, "multiplier": None},
	"per 1 000 inwoners van 15 tot 45 jaar": {"unit": None, "multiplier": None},
	"per 1 000 inwoners op 1 januari": {"unit": None, "multiplier": None},
	"per 1 000 inwoners": {"unit": None, "multiplier": None},
	"per 1 000 inhabitants": {"unit": None, "multiplier": None},
	"per 1 000 huishoudens": {"unit": None, "multiplier": None},
	"per 1 000 gehuwde vrouwen": {"unit": None, "multiplier": None},
	"per 1 000 gehuwde mannen": {"unit": None, "multiplier": None},
	"per 1 000 geborenen": {"unit": None, "multiplier": None},
	"per 1 000 geboren kinderen": {"unit": None, "multiplier": None},
	"per 1 000 geboorten": {"unit": None, "multiplier": None},
	"per 1 000 echtparen": {"unit": None, "multiplier": None},
	"per 1 000 born children": {"unit": None, "multiplier": None},
	"per 1 000 births": {"unit": None, "multiplier": None},
	"per 1 000 ": {"unit": None, "multiplier": None},
	"per 1 000": {"unit": None, "multiplier": None},
	"passenger kilometres ": {"unit": QUDT_UNIT.KILOM, "multiplier": None},
	"passenger kilometres": {"unit": QUDT_UNIT.KILOM, "multiplier": None},
	"omschrijving": {"unit": None, "multiplier": None},
	"o/oo": {"unit": QUDT_UNIT.PERMILLE, "multiplier": None},
	"number x 1 000": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"number per 1 000 persons": {"unit": None, "multiplier": None},
	"number of notifications": {"unit": None, "multiplier": None},
	"number": {"unit": QUDT_UNIT.COUNT, "multiplier": None},
	"niet beschikbaar": {"unit": None, "multiplier": None},
	"name": {"unit": None, "multiplier": None},
	"naam": {"unit": None, "multiplier": None},
	"m³": {"unit": QUDT_UNIT.M3, "multiplier": None},
	"m²": {"unit": QUDT_UNIT.M2, "multiplier": None},
	"mm": {"unit": QUDT_UNIT.C_M, "multiplier": 0.1},
	"mln uren": {"unit": QUDT_UNIT.HR, "multiplier": 1000000},
	"mln tonkm": {"unit": QUDT_UNIT.KILOGM_PER_KILOM, "multiplier": 1000000000},
	"mln m3 aardgasequivalenten": {"unit": QUDT_UNIT.M3, "multiplier": 1000000},  # add aardgasequivalenten
	"mln m3": {"unit": QUDT_UNIT.M3, "multiplier": 1000000},
	"mln km": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000000},
	"mln kgs": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000000},
	"mln kg droge stof": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000000},
	"mln kg": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000000},
	"mln kWh": {"unit": QUDT_UNIT.KILOW_HR, "multiplier": 1000000},
	"mln hours": {"unit": QUDT_UNIT.HR, "multiplier": 1000000},
	"mln euros": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000},
	"mln euro": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000},
	"mln USD": {"unit": QUDT_UNIT.CCY_USD, "multiplier": 1000000},
	"mln Sm³": {"unit": None, "multiplier": None},  # add Sm³
	"mln ": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000000},
	"mld reizigerskilometers": {"unit": QUDT_UNIT.KILOM, "multiplier": 1000000000},  # add reizigers
	"mld euro": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000000},
	"mld acid-equivalents": {"unit": None, "multiplier": None},  # add acid-equivalents
	"mld Sm³": {"unit": None, "multiplier": None},  # add Sm³
	"ml/g": {"unit": QUDT_UNIT.MILLIL_PER_GM, "multiplier": None},
	"minutes": {"unit": QUDT_UNIT.MIN, "multiplier": None},
	"minuten": {"unit": QUDT_UNIT.MIN, "multiplier": None},
	"millon euros": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000},
	"million m3 natural gas equivalents": {"unit": QUDT_UNIT.M3, "multiplier": 1000000},  # add natural gas equivalents
	"million kwh": {"unit": QUDT_UNIT.KILOW_HR, "multiplier": 1000000},
	"million km": {"unit": QUDT_UNIT.KILOM, "multiplier": 1000000},
	"million kgs": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000000},
	"million kg": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000000},
	"million hours": {"unit": QUDT_UNIT.HR, "multiplier": 1000000},
	"million euros ": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000},
	"million euros": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000},
	"million euro": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000},
	"million USD": {"unit": QUDT_UNIT.CCY_USD, "multiplier": 1000000},
	"miljoen stuks": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000000},
	"miljard kg CO2-equivalent": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000000000},  # add CO2-equivalent
	"miljard euro": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000000},
	"miilion kg": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000000},
	"mg/l": {"unit": QUDT_UNIT.MILLIGM_PER_L, "multiplier": None},
	"meter": {"unit": QUDT_UNIT.M, "multiplier": None},
	"mensjaren": {"unit": QUDT_UNIT.YR, "multiplier": None},
	"megawatt(piek)": {"unit": QUDT_UNIT.MEGAW, "multiplier": None},
	"megawatt": {"unit": QUDT_UNIT.MEGAW, "multiplier": None},
	"man-years": {"unit": QUDT_UNIT.YR, "multiplier": None},
	"m3/m2": {"unit": QUDT_UNIT.M3_PER_M2, "multiplier": None},
	"m3": {"unit": QUDT_UNIT.M3, "multiplier": None},
	"m2": {"unit": QUDT_UNIT.M2, "multiplier": None},
	"liter": {"unit": QUDT_UNIT.L, "multiplier": None},
	"kton": {"unit": QUDT_UNIT.KILOTONNE, "multiplier": None},
	"km²": {"unit": QUDT_UNIT.KILOM2, "multiplier": None},
	"km2": {"unit": QUDT_UNIT.KILOM2, "multiplier": None},
	"km": {"unit": QUDT_UNIT.KILOM, "multiplier": None},
	"klasse": {"unit": None, "multiplier": None},
	"kilometer": {"unit": QUDT_UNIT.KILOM, "multiplier": None},
	"kg/ha": {"unit": QUDT_UNIT.KILOGM_PER_HA, "multiplier": None},
	"kg per inwoner": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.KILOGM_PER_NUM
	"kg per capita": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.KILOGM_PER_NUM
	"kg droge stof/m3": {"unit": QUDT_UNIT.KILOGM_PER_M3, "multiplier": None},
	"kg droge stof/ kg BZV": {"unit": QUDT_UNIT.KILOGM_PER_KILOGM, "multiplier": None},
	"kg droge stof/ i.e.": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.KILOGM_PER_NUM
	"kg": {"unit": QUDT_UNIT.KILOGM, "multiplier": None},
	"kans": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"kWp": {"unit": QUDT_UNIT.KILOW, "multiplier": None},
	"kWh/m2": {"unit": QUDT_UNIT.KILOW_HR_PER_M2, "multiplier": None},
	"kWh per m2": {"unit": QUDT_UNIT.KILOW_HR_PER_M2, "multiplier": None},
	"kWh": {"unit": QUDT_UNIT.KILOW_HR, "multiplier": None},
	"kW": {"unit": QUDT_UNIT.KILOW, "multiplier": None},
	"jaren": {"unit": QUDT_UNIT.YR, "multiplier": None},
	"jaar ": {"unit": QUDT_UNIT.YR, "multiplier": None},
	"jaar": {"unit": QUDT_UNIT.YR, "multiplier": None},
	"indexcijfers 2021=100": {"unit": None, "multiplier": None},
	"index basisjaar=100": {"unit": None, "multiplier": None},
	"index 2021=100": {"unit": None, "multiplier": None},
	"index 2015=100": {"unit": None, "multiplier": None},
	"in % van verzonden facturen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van totaal lasten": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van totaal exploitanten": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van totaal baten": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van totaal aantal organisaties": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van ontvangen facturen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van omzet via website/app": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van omzet via EDI": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van maximaal op te bouwen jaren": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van laatste contact in de gemeente": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van laatste contact": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van jachthavens": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van inkoop via website/app": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van inkoop via EDI": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van het verbruik": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van het totaal aantal sportclubs": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van bedrijven met verbreding": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van bbp": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van arbeidsvolume werkzame personen in loondienst": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van arb.volume wp. niet in loondienst": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van arb.volume wp. in loondienst": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % van aantal inwoners": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % ondervonden delicten": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % of use": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % of labour volume volunteers": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % of labour volume employees": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"in % bbp": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"hours": {"unit": QUDT_UNIT.HR, "multiplier": None},
	"hour": {"unit": QUDT_UNIT.HR, "multiplier": None},
	"hm": {"unit": QUDT_UNIT.HECTOM, "multiplier": None},
	"hectares": {"unit": QUDT_UNIT.HA, "multiplier": None},
	"hectare": {"unit": QUDT_UNIT.HA, "multiplier": None},
	"ha / 1 000 inwoners": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.HA_PER_NUM
	"ha": {"unit": QUDT_UNIT.HA, "multiplier": None},
	"grams/km": {"unit": QUDT_UNIT.GM_PER_KILOM, "multiplier": None},
	"gram/km": {"unit": QUDT_UNIT.GM_PER_KILOM, "multiplier": None},
	"graden Celsius": {"unit": QUDT_UNIT.DEG_C, "multiplier": None},
	"gemiddelde uren": {"unit": QUDT_UNIT.HR, "multiplier": None},
	"gemiddelde score": {"unit": None, "multiplier": None},
	"gemiddelde saldo van de deelvragen": {"unit": None, "multiplier": None},
	"gemiddelde": {"unit": QUDT_UNIT.NUM, "multiplier": None},
	"gemiddeld m3": {"unit": QUDT_UNIT.M3, "multiplier": None},
	"gemiddeld kWh": {"unit": QUDT_UNIT.KILOW_HR, "multiplier": None},
	"gemiddeld %": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"gemiddeld": {"unit": QUDT_UNIT.NUM, "multiplier": None},
	"gem kWh": {"unit": QUDT_UNIT.KILOW_HR, "multiplier": None},
	"g/kg droge stof": {"unit": QUDT_UNIT.GM_PER_KILOGM, "multiplier": None},
	"g droge stof/kg": {"unit": QUDT_UNIT.GM_PER_KILOGM, "multiplier": None},
	"euros per pollution unit": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_NUM
	"euros per housing unit": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_NUM
	"euros per hectare": {"unit": QUDT_UNIT.CCY_EUR_PER_M2, "multiplier": 0.0001},
	"euros": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": None},
	"euro/litre": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_L
	"euro/liter": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_L
	"euro/kg": {"unit": None, "multiplier": None},
	"euro/kWh": {"unit": QUDT_UNIT.CCY_EUR_PER_KILOW_HR, "multiplier": None},
	"euro/inwoner": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_NUM
	"euro/inhabitant": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_NUM
	"euro per woonruimte": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_NUM
	"euro per vervuilingseenheid": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_NUM
	"euro per maand": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_MO
	"euro per m3": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_M3
	"euro per kWh": {"unit": QUDT_UNIT.CCY_EUR_PER_KILOW_HR, "multiplier": None},
	"euro per ha": {"unit": QUDT_UNIT.CCY_EUR_PER_M2, "multiplier": 0.0001},
	"euro per 1 000 kg": {"unit": None, "multiplier": None},
	"euro": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": None},
	"eenheid": {"unit": None, "multiplier": None},
	"description": {"unit": None, "multiplier": None},
	"days": {"unit": QUDT_UNIT.DAY, "multiplier": None},
	"datum": {"unit": None, "multiplier": None},
	"dagen per jaar": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.DAY_PER_YR
	"dagen": {"unit": QUDT_UNIT.DAY, "multiplier": None},
	"dag": {"unit": QUDT_UNIT.DAY, "multiplier": None},
	"d": {"unit": QUDT_UNIT.DAY, "multiplier": None},
	"coëfficiënt": {"unit": None, "multiplier": None},
	"coefficient": {"unit": None, "multiplier": None},
	"code": {"unit": None, "multiplier": None},
	"cm": {"unit": QUDT_UNIT.CENTIM, "multiplier": None},
	"bn euros": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000000},
	"bn Sm³": {"unit": None, "multiplier": None},  # add Sm³
	"billion passenger kilometres ": {"unit": QUDT_UNIT.KILOM, "multiplier": 1000000000},
	"billion kgs CO2-equivalent": {"unit": None, "multiplier": None},  # add CO2-equivalent
	"billion euros": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000000},
	"billion euro": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000000000},
	"balance of positive and negative answers": {"unit": None, "multiplier": None},
	"average score": {"unit": None, "multiplier": None},
	"average balance of the subquestions": {"unit": None, "multiplier": None},
	"average": {"unit": QUDT_UNIT.NUM, "multiplier": None},
	"are": {"unit": QUDT_UNIT.ARE, "multiplier": None},
	"afkorting": {"unit": None, "multiplier": None},
	"adressen per km2": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.NUM_PER_KILOM2
	"admissions per 10 000 of the population": {"unit": None, "multiplier": None},
	"absoluut": {"unit": QUDT_UNIT.COUNT, "multiplier": None},
	"ab_so_luut": {"unit": QUDT_UNIT.COUNT, "multiplier": None},
	"aantal x 1 000": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"aantal woningen per km²": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.NUM_PER_KILOM2
	"aantal uren": {"unit": QUDT_UNIT.HR, "multiplier": None},
	"aantal personen": {"unit": QUDT_UNIT.COUNT, "multiplier": None},
	"aantal per 10 000 inwoners": {"unit": None, "multiplier": None},
	"aantal per 1 000 personen": {"unit": None, "multiplier": None},
	"aantal opnamen per 10 000 personen": {"unit": None, "multiplier": None},
	"aantal meldingen": {"unit": QUDT_UNIT.COUNT, "multiplier": None},
	"aantal maanden": {"unit": QUDT_UNIT.MO, "multiplier": None},
	"aantal km": {"unit": QUDT_UNIT.KILOM, "multiplier": None},
	"aantal inwoners per km²": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.NUM_PER_KILOM2
	"aantal": {"unit": QUDT_UNIT.COUNT, "multiplier": None},
	"Wh/kg": {"unit": QUDT_UNIT.W_HR_PER_KILOGM, "multiplier": None},
	"USD": {"unit": QUDT_UNIT.CCY_USD, "multiplier": None},
	"TJ": {"unit": QUDT_UNIT.TERAJ, "multiplier": None},
	"Safety rating": {"unit": None, "multiplier": None},
	"Procentpunt": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"Percentage point": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"Per mln van gemiddelde bevolking": {"unit": None, "multiplier": None},
	"Per mln of the average population": {"unit": None, "multiplier": None},
	"Per 100 000 of the average population": {"unit": None, "multiplier": None},
	"Per 10 000 inwoners": {"unit": None, "multiplier": None},
	"Per 1,000 live born children": {"unit": None, "multiplier": None},
	"Per 1 000 inwoners": {"unit": None, "multiplier": None},
	"Per 1 000 ": {"unit": None, "multiplier": None},
	"PJ": {"unit": QUDT_UNIT.PETAJ, "multiplier": None},
	"Numbers": {"unit": QUDT_UNIT.COUNT, "multiplier": None},
	"Number of days": {"unit": QUDT_UNIT.DAY, "multiplier": None},
	"Number": {"unit": QUDT_UNIT.COUNT, "multiplier": None},
	"None": {"unit": None, "multiplier": None},
	"Naam": {"unit": None, "multiplier": None},
	"Mln tonkilometer": {"unit": QUDT_UNIT.KILOGM_PER_KILOM, "multiplier": 1000000000},
	"Minutes": {"unit": QUDT_UNIT.MIN, "multiplier": None},
	"Minuten": {"unit": QUDT_UNIT.MIN, "multiplier": None},
	"MWh": {"unit": QUDT_UNIT.MEGAW_HR, "multiplier": None},
	"MW": {"unit": QUDT_UNIT.MEGAW, "multiplier": None},
	"MJ/h": {"unit": QUDT_UNIT.MEGAJ_PER_HR, "multiplier": None},
	"Levend geboren jongens per 1 000 levend geboren meisjes": {"unit": None, "multiplier": None},
	"Index (1995=100)": {"unit": None, "multiplier": None},
	"In % van alle werknemers": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"In % totaal aantal productinnovatoren": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"In % totaal aantal procesinnovatoren": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"In % ondervonden delicten waarvan geen melding gemaakt": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"In % ondervonden delicten": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"In % bepaalde leeftijdsklasse": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"Ginicoëfficiënt": {"unit": None, "multiplier": None},
	"Gini coefficient": {"unit": None, "multiplier": None},
	"Getal": {"unit": None, "multiplier": None},
	"Gemiddelde van de deelindicatoren": {"unit": None, "multiplier": None},
	"GJ/1000 kg": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.GigaJ_PER_TONNE
	"Full-time equivalent": {"unit": None, "multiplier": None},
	"Euro/year": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_YR
	"Euro/m3": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_M3
	"Euro/kWh": {"unit": QUDT_UNIT.CCY_EUR_PER_KILOW_HR, "multiplier": None},
	"Euro/jaar": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.CCY_EUR_PER_YR
	"Coëfficiënt": {"unit": None, "multiplier": None},
	"Coëfficient": {"unit": None, "multiplier": None},
	"Coefficient": {"unit": None, "multiplier": None},
	"Code": {"unit": None, "multiplier": None},
	"Average of the components": {"unit": None, "multiplier": None},
	"Aantal dagen": {"unit": QUDT_UNIT.DAY, "multiplier": None},
	"Aantal": {"unit": QUDT_UNIT.COUNT, "multiplier": None},
	"Aandeel van bedrijven met afgeronde innovaties": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"2021=100": {"unit": None, "multiplier": None},
	"2021 =100": {"unit": None, "multiplier": None},
	"2021 = 100": {"unit": None, "multiplier": None},
	"2020=100": {"unit": None, "multiplier": None},
	"2020 =100": {"unit": None, "multiplier": None},
	"2017=100": {"unit": None, "multiplier": None},
	"2015=100": {"unit": None, "multiplier": None},
	"2015 = 100": {"unit": None, "multiplier": None},
	"2012=100": {"unit": None, "multiplier": None},
	"2011=100": {"unit": None, "multiplier": None},
	"2010=100": {"unit": None, "multiplier": None},
	"2006=100": {"unit": None, "multiplier": None},
	"2005=100": {"unit": None, "multiplier": None},
	"2000=100": {"unit": None, "multiplier": None},
	"2000 = 100": {"unit": None, "multiplier": None},
	"1995=100": {"unit": None, "multiplier": None},
	"1990=100": {"unit": None, "multiplier": None},
	"1985=100": {"unit": None, "multiplier": None},
	"1980=100": {"unit": None, "multiplier": None},
	"1975=100": {"unit": None, "multiplier": None},
	"1969=100": {"unit": None, "multiplier": None},
	"1900 = 100": {"unit": None, "multiplier": None},
	"1000m3": {"unit": QUDT_UNIT.M3, "multiplier": 1000},
	"1000kWh": {"unit": QUDT_UNIT.KILOW_HR, "multiplier": 1000},
	"1000 v.e.": {"unit": None, "multiplier": None},
	"1000 ton": {"unit": QUDT_UNIT.TONNE, "multiplier": 1000},
	"1000 stuks/ha": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.NUM_PER_HA
	"1000 stuks": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"1000 pieces/ha": {"unit": None, "multiplier": None},  # suggestion: QUDT_UNIT.NUM_PER_HA
	"1000 pieces": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"1000 pcs": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"1000 m3": {"unit": QUDT_UNIT.M3, "multiplier": 1000},
	"1000 kg": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000},
	"1000 kWh": {"unit": QUDT_UNIT.KILOW_HR, "multiplier": 1000},
	"1000 euro": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000},
	"1000 arbeidsjaren": {"unit": QUDT_UNIT.YR, "multiplier": 1000},
	"1000 USD": {"unit": QUDT_UNIT.CCY_USD, "multiplier": 1000},
	"1000 TEU": {"unit": None, "multiplier": None},
	"1000  kWh": {"unit": QUDT_UNIT.KILOW_HR, "multiplier": 1000},
	"100 ha": {"unit": QUDT_UNIT.HA, "multiplier": 100},
	"1,000 persons": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
	"1,000 m3": {"unit": QUDT_UNIT.M3, "multiplier": 1000},
	"1,000 kg": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000},
	"1,000 kWh": {"unit": QUDT_UNIT.KILOW_HR, "multiplier": 1000},
	"1,000 full-time equivalent jobs": {"unit": None, "multiplier": None},
	"1,000 fte jobs": {"unit": None, "multiplier": None},
	"1,000 euros": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000},
	"1,000 euro": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000},
	"1,000 FTEs": {"unit": None, "multiplier": None},
	"1 000 years of employment": {"unit": QUDT_UNIT.YR, "multiplier": 1000},
	"1 000 varkenseenheden": {"unit": None, "multiplier": None},
	"1 000 v.e.": {"unit": None, "multiplier": None},
	"1 000 tonnes": {"unit": QUDT_UNIT.TONNE, "multiplier": 1000},
	"1 000 ton": {"unit": QUDT_UNIT.TONNE, "multiplier": 1000},
	"1 000 teu": {"unit": None, "multiplier": None},
	"1 000 pollution equivalent": {"unit": None, "multiplier": None},
	"1 000 pluimvee-eenheden": {"unit": None, "multiplier": None},
	"1 000 m³": {"unit": QUDT_UNIT.M3, "multiplier": 1000},
	"1 000 m²": {"unit": QUDT_UNIT.M2, "multiplier": 1000},
	"1 000 m3": {"unit": QUDT_UNIT.M3, "multiplier": 1000},
	"1 000 m2": {"unit": QUDT_UNIT.M2, "multiplier": 1000},
	"1 000 km": {"unit": QUDT_UNIT.KILOM, "multiplier": 1000},
	"1 000 kg fosfaat": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000},
	"1 000 kg": {"unit": QUDT_UNIT.KILOGM, "multiplier": 1000},
	"1 000 kWh": {"unit": QUDT_UNIT.KILOW_HR, "multiplier": 1000},
	"1 000 inhabitant equivalents": {"unit": None, "multiplier": None},
	"1 000 i.e.": {"unit": None, "multiplier": None},
	"1 000 ha": {"unit": QUDT_UNIT.HA, "multiplier": 1000},
	"1 000 full time equivalents": {"unit": None, "multiplier": None},
	"1 000 euros": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000},
	"1 000 euro": {"unit": QUDT_UNIT.CCY_EUR, "multiplier": 1000},
	"1 000 dollar": {"unit": QUDT_UNIT.CCY_USD, "multiplier": 1000},
	"1 000 arbeidsjaren": {"unit": QUDT_UNIT.YR, "multiplier": 1000},
	"1 000 CFK12-equivalents": {"unit": None, "multiplier": None},
	"0/00": {"unit": QUDT_UNIT.PERMILLE, "multiplier": None},
	"% ‘great nuisance’": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% ‘Occurs sometimes’": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% ziektedagen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% weleens (vaak/soms)": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% weidedagen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% vrouwen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% volumemutaties": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% volume changes": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% volume change": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% veel overlast": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van zonder partner": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van zelfstandigen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van werkzame personen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van werkzame beroepsbevolking": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van werknemers": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van vestigingen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van verzonden facturen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van totale lasten": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van totale baten": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van totale CO2 emissie": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van totaal watersportclubs": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van totaal geregistreerde misdrijven": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van totaal geregistreerde diefstallen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van totaal energieverbruik": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van totaal eindverbruik energie": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van totaal arbeidsuren vrijwilligers": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van totaal aantal musea": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van totaal aantal leden": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van studenten met buitenlandervaring": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van ontvangen facturen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van omzet via website/app": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van omzet via EDI": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van omzet": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van met partner": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van inwoners 15 jaar of ouder": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van inkoop via website/app": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van inkoop via EDI": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van het aantal inwoners vanaf 15 jaar": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van droge stof": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van de werkzame bevolking ": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van de werkzame bevolking": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van de bevolking": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van bevolking": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van bedrijven met ransomware-aanval": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van bedrijven met kosten door intern incident": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van bedrijven met kosten door incident": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van bedrijven met kosten door aanval": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van bedrijven met drie of meer opdrachtgevers": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van bedrijven met andere kosten": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van bedrijven met ICT-beveiligingsbeleid": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van bedrijven die losgeld hebben betaald": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van bedrijven die een account op sociale media gebruiken": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van bedrijven": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% van alle studenten": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% value added": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% vaak": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% total liabilities": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% total energy cons.": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% total assets": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% totaal vorderingen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% totaal schulden": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% toegevoegde waarde": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers verzocht om meer beelden": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers verzocht om geld": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers met lichamelijk letsel": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers met gekpieerde gegevens/documenten waarbij de dader geld vroeg": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers met gekpieerde gegevens/documenten": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers met gekopieerde gegevens of bestanden waarbij dader geld vroeg": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers met gekopieerde gegevens of bestanden": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers met geblokkeerd apparaat of bestanden waarbij dader geld vroeg": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers met geblokkeerd apparaat of bestanden": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers met (tijdelijk) geblokkeerd account waarbij dader geld vroeg": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers met (tijdelijk) geblokkeerd account": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers geen melding/aangifte": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers diefstal scooter": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers ": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% slachtoffers": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% oppervlakte land": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% of total revenues": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% of total costs": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% of total CO2 emission": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% of the total number of sports clubs": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% of enterprises realised innovations": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% of GDP": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% number of visitors": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% droge stof": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% disposable income": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% buitenland overwogen maar niet gegaan": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% beschikbaar inkomen": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% bedrijven met omzet via platforms": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% bbp": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% altijd of vaak": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% aanwezig": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% aantal bezoekers": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% WOZ value": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% WOZ": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% GDP": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% (zie toelichting)": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% (zeer) tevreden": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% (van het bbp)": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% (helemaal) eens": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% (heel) tevreden": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% (heel) groot": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% 'veel overlast'": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% ' komt wel eens voor'": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"% ": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	"%": {"unit": QUDT_UNIT.PERCENT, "multiplier": None},
	" x 1 000": {"unit": QUDT_UNIT.COUNT, "multiplier": 1000},
}

if __name__ == "__main__":
    from odata_graph import engine
    from odata_graph.sparql_controller import QUDT
    from rdflib import Graph, URIRef, Literal, XSD
    from tqdm import tqdm
    import config

    # Uncomment when updating QUDT to a new version using a TTL file
    # generate_defined_namespace(ttl_file=config.QUDT_GRAPH,
    #                            py_file='./odata_graph/namespaces/_QUDT_UNIT.py',
    #                            ns_uri='http://qudt.org/schema/qudt/Unit')

    print("Updating graph with new QUDT units...")

    onderwerpen_context_id = URIRef("http://onderwerpen")
    onderwerpen_graph = engine.graph.get_context(onderwerpen_context_id)

    # Get all measure-unit pairs from the 'onderwerpen' graph that use the old predicate
    cbs_units_to_process = list(onderwerpen_graph.subject_objects(QUDT.unitOfSystem))
    print(f"Found {len(cbs_units_to_process)} measures with unitOfSystem predicate.")

    updated_count = 0
    for measure_uri, unit_literal in tqdm(cbs_units_to_process, desc="Updating graph with new QUDT units", bar_format=config.TQDM_BAR_FMT):
        unit_string = str(unit_literal)

        if unit_string in UNIT_DICT:
            mapping = UNIT_DICT[unit_string]
            new_unit = mapping.get("unit")
            multiplier = mapping.get("multiplier")

            # Remove old triples from the specific context
            onderwerpen_graph.remove((measure_uri, QUDT.unit, None))
            onderwerpen_graph.remove((measure_uri, QUDT.conversionMultiplier, None))

            # Add new triples to the specific context
            if new_unit:
                onderwerpen_graph.add((measure_uri, QUDT.unit, new_unit))
                updated_count += 1

            if multiplier is not None:
                onderwerpen_graph.add((measure_uri, QUDT.conversionMultiplier, Literal(multiplier, datatype=XSD.integer if multiplier.is_integer() else XSD.decimal)))

    print(f"Updated {updated_count} measures with new units.")

    # Serialize the entire conjunctive graph, which includes the modified 'onderwerpen' context
    engine.graph.serialize(destination=config.GRAPH_FILE, format='trig', encoding='utf-8')
    print(f"Graph updated and saved to {config.GRAPH_FILE}")

    print("Making graph for uploading to GRAPHDB")
    qudt_context = URIRef("http://qudt")
    qudt_graph = Graph(engine.graph.store, identifier=qudt_context)
    qudt_graph.parse(config.QUDT_GRAPH, format='turtle')

    engine.graph.serialize(config.GRAPH_FILE.replace('.trig', '-qudt.trig'), format='trig', encoding='utf-8')
